language: node_js
sudo: true
cache:
  directories:
    - "node_modules"

node_js:
  - "9"

services:
  - postgresql

env:
  global:
    - NODE_ENV=test

before_install:
  - psql -c 'create database transaction;' -U postgres
  - psql -c "CREATE USER foo WITH PASSWORD 'bar';" -U postgres
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build --debug

install:
  - npm install
  - cp config/database.ci.json config/database.json
  - npm run sequelize db:migrate

script:
  - npm run coverage

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
  - npm run lint

after_success:
  - npm run coveralls
